### ISSUE TITLE
Any ideas for faster fail-over for script loading?

### ISSUE THREAD

**Issue by niyazpk** [h5bp/lazyweb-requests#107]
From h5bp:

```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
    window.jQuery || document.write('<script src="js/vendor/jquery-1.8.3.min.js"><\/script>')
</script>
```

Can we please investigate the possibility of providing a timeout to the first request so that it can switch-over soon rather than late to the local copy?

It might take a small loader script to accomplish this, but it is nice to have, especially if you are using something like [cdnjs](http://cdnjs.com) for multiple scripts.

**Comment by arthurvr** [comment]
> Another option would be to use Modernizr's load function. Here's an example:

These days `Modernizr.load` and yepnope are deprecated.

**Comment by stuartpb** [comment]
> These days Modernizr.load and yepnope are deprecated.

What's the alternative? `var scr=document.createElement('script'); scr.src=whatever; document.head.appendChild(scr)`?

**Comment by roblarsen** [comment]
>These days Modernizr.load and yepnope are deprecated.

If you ignore Github and the specter of 3.0, Modernizr.load is alive and well.
