### ISSUE TITLE
CSS Polyfill Framework

### ISSUE THREAD

**Issue by philipwalton** [h5bp/lazyweb-requests#110]
Hey everyone,

Yesterday I started to try my hand at writing a new Flexbox polyfill, and it occurred to me that most CSS polyfills share a lot of the same needs:
- XHR for the stylesheets
- Scan the CSS for the properties/values you want to polyfill
- Handle media queries and when certain rules do/don't apply

It would be great to have a standard library that did a lot of this stuff for you and allowed polyfill authors to build on top of it. A robust library would encourage more people to write polyfills, and it would make polyfills smaller in size since they could share a lot of existing code.

My thought was you could pass in the properties and values you care about, and it would return a collection of selectors that matched. It would also trigger events for things like when new media queries matched based on screen resizing and whatnot.

Does anyone know if there's work being done on something like this currently? If not, I'd be happy to take a stab at it and would love to collaborate if anyone is interested.

**Comment by paulirish** [comment]
@philipwalton this is totally awesome. i never said it but its true.

https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#css-core-modules is FULL of tiny polyfills shipping a big CSS parser in JS. kind of hilarious. :)

<hr>

http://www.hitchjs.com/ also explored this area

and now a standard is being picked up here: https://github.com/w3c/css-houdini-drafts/tree/master/css-parser-api

**Comment by stuartpb** [comment]
Houdini looks awesome. Glad to see the upstream thinking move beyond "CSS is for minor presentation flair and should never be relied of to the extent they need to be polyfilled", since that's plainly backwards (flexbox and touch-action being two extremely important CSS properties developers have to rely on for all practical purposes).
