### ISSUE TITLE
Make the forward button useful

### ISSUE THREAD

**Issue by drdamour** [h5bp/lazyweb-requests#112]
i feel bad for the forward button in the browser, it's so rarely useful.  Look what IE did to it!
![image](https://f.cloud.github.com/assets/1514496/240646/afdd4a46-8938-11e2-9ba5-d492aed34bd5.png)
poor guy is so small.  firefox is even meaner!
![image](https://f.cloud.github.com/assets/1514496/240649/f9d8a2da-8938-11e2-9c77-3f8052cdd6c1.png)
he just pretends it doesn't even exist unless he needs something from him.  We all have friends like this, and we despise them.

let's make the forward button a first class citizen, here's how i propose we do it.

Have you been to one of these newer-ish articles that have one of these at the bottom:
![image](https://f.cloud.github.com/assets/1514496/240652/5b05de1a-8939-11e2-8888-ed6311858f9e.png)
or a pagenation listing, or any page that has a semantic concept of next?  I'm sure you have, how about google search results?

Let's make a plugin for the various browsers that attempts to identify the semantic next automatically and enables our good buddy the forward button to take us there when we click it or click the forward button on our mouse or alt+right arrow (or gasp shift+backspace) it takes us to the next page.  Let's make the forward button from being useless 90% of the time we are on our browser[citation needed] to useful 90% of the time.

let's take it a step futher, let's figure out a way to allow the semantics to be defined explicitly in the markup of a document so our plugin can look for it and know what the next page was per the content authors intent!   something like

``` html
<link rel="next-page" href="/next-page-url-here" />
```

1st ? will be what to do when the user is within their existing history (IE when the forward button is active now a days).  In that case i would expect to be taken to their real history, not the suggested history, but we could make this an option or something, open to ideas.

what are your guys thoughts?

**Comment by olejorgenb** [comment]
As already mentioned: Good old opera (<= 12 - before degrading to a chromium clone) appreciated the forward button. See that double forward button in [screenshot (](http://www.downloadcollection.com/graphics/largeimages/opera_for_linux-686245.png)? That did just what you ask for (based on heuristics)

**Comment by drdamour** [comment]
@olejorgenb that's neat, i had forgotten about that...but since it was non standard it wasn't tied to the most buttons etc.   it does offer an answer to the "what if you have forward history already"
