### ISSUE TITLE
Man page viewer built with web standards

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/lazyweb-requests#114]
Writing man pages by hand is pretty horrible. For this reason, most people auto-generate man pages based on Markdown or something else, nowadays.

But it doesn’t have to be that way.

Imagine having a JavaScript library that takes a man page as a string (e.g. https://github.com/mathiasbynens/luamin/blob/master/man/luamin.1) and renders it as HTML. It would be immensely useful.

Currently the workflow for editing a man page by hand goes something like this:

1. Edit man page source file.
2. Run `man ./man-page-source-file.1`.
3. Confirm the resulting man page looks alright. If it doesn’t, `GOTO 1`.

Having such a library would make it possible to edit man pages right in the browser, complete with a live preview and everything — the workflow would then be much easier and more efficient. Hipsters around the world would rejoice.

**Comment by roperzh** [comment]
Hello, everyone!

This issue inspired me to build two projects:

- [Jroff](https://github.com/roperzh/jroff): a man page parser written in JavaScript, featuring basic support for `groff` commands and support for `an` and `doc` macros.

- [Grapse](http://www.roperzh.com/grapse/): a web application that uses Jroff to parse man pages in real time ( very similar to dillinger, but for man pages ).

Both projects are still in beta, but everyone is more than welcome to contribute / criticize / help in any way :).

cc: @mathiasbynens @d0ugal @SeriousM

**Comment by mathiasbynens** [comment]
@roperzh Woah, nice work! :+1:
