### ISSUE TITLE
Animated gif tooling

### ISSUE THREAD

**Issue by paulirish** [h5bp/lazyweb-requests#116]
@slexaxton's gifify script is pretty good but our common video->animated gif workflow could be much better

1) animated webp (coming to chrome and FF soon, likely)
2) supporting "true-color" GIFs http://phil.ipal.org/tc.html

**Comment by arthurvr** [comment]
> I would be interested in us doing something similar to mothereffinganimatedgif.com where we provide an easy tool to drag and drop a video and get back either an animated gif or webp file.

Aren't there enough tools that already do this? I use http://gfycat.com/ sometimes.

**Comment by fent** [comment]
I've been using MakeGIF Video Capture https://chrome.google.com/webstore/detail/makegif-video-capture/cnhdjbfjheoohmhpakglckehdcgfffbl

It has a few features, like quality, framerate, cropping, and it works well. But it's not maintained anymore.

**Comment by kornelski** [comment]
And if you need GIF to look nice, there's https://gif.ski
