### ISSUE TITLE
Create watch lists of projects

### ISSUE THREAD

**Issue by thanpolas** [h5bp/lazyweb-requests#146]
Both as an author and as a consumer i want to have a high-level overview of the projects i am following. 

As an author mostly for vanity reasons, as a consumer to keep track of any updates.

A dashboard mashing up stats, data and history in awesome charts for every project from all possible sources, github, npm, bower, gems, pip, whatnot...

So in a glimpse i'd like to see how my watched projects have been doing for the past year, downloads, stars, issues, commits ...

**Comment by arthurvr** [comment]
@ankurkaushal What's the progress on this?

**Comment by ankurkaushal** [comment]
@arthurvr Well, to be honest, didn't really got the time to start working on it during the holidays due to personal reasons. Will probably try to start on it soon.

**Comment by arthurvr** [comment]
ping @ankurkaushal Just wondering if you had any more progress on this one?

**Comment by ankurkaushal** [comment]
Sorry @arthurvr, haven't been able to start this one.
