### ISSUE TITLE
GitHub badges in SVG format

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/lazyweb-requests#150]
A lot of GitHub repositories have badges like these in their README:

![Coveralls](http://img.shields.io/coveralls/resque/resque.png)
![Gittip](http://img.shields.io/gittip/jsfiddle.png)
![Travis CI](http://img.shields.io/travis-ci/rails/rails.png)
![Generic](http://img.shields.io/cheez/whiz.png?color=yellow)

There are several services that can be used to serve these badge images based on some URL parameters, e.g. [shields.io](http://shields.io/) ([repo](https://github.com/gittip/img.shields.io)).

Currently these badges are all bitmaps (usually in JPG or PNG format). It would be nice to have them in SVG format, for the following reasons:
- vector images still look nice on high-resolution displays
- hackability; creating a badge with different colors or text is just a matter of editing the SVG file in a text editor
- likely, bandwidth savings (for the services that serve these badge images **and** for end users)
### TODO
- [x] Remake these images as a static example SVG file
- [ ] Convince an existing badge service to serve SVG responses instead of the bitmaps they’re sending out now (optionally based on a new URL parameter)

Any SVG gurus/ninjas/unicorns out there that want to give the first task a try?

**Comment by hhfrancois** [comment]
Hi, thank for the service.
your service Have it a max delivery ?
Cause with 7 badges in my site, I have an error.

**Comment by espadrine** [comment]
@hhfrancois Thanks for telling us! We hope we fixed it. Tell us if it works better.

As a side-node, it may be unstable this week, but will be better next week.

**Comment by hhfrancois** [comment]
@espadrine Thank for the response.

**Comment by svoop** [comment]
@espadrine I don't find a better place to ask this: How about adding beerpay.io as well?

**Comment by espadrine** [comment]
@svoop Don't hesitate to [create an issue](https://github.com/badges/shields/issues/new) on the project!

**Comment by calidion** [comment]
hi, all 
the service is very unstable.

i can easily get unresponsive state.
can this be improved?

**Comment by niksmac** [comment]
here from [here](http://shields.io)

**Comment by cbanowsky** [comment]
the custome badges are fun if nothing else: 
 ![like this one](https://img.shields.io/badge/fuck%20you-%2B1-brightgreen.svg?style=social)

**Comment by Llewellynvdm** [comment]
The downloads __total__ badges are not working for github.
