### ISSUE TITLE
Online Yeoman builder for quicker scaffolding projects structures

### ISSUE THREAD

**Issue by kbariotis** [h5bp/lazyweb-requests#154]
Is anyone interested in creating an online service for Yeoman to scaffold projects?

The problem is that i don't want to use terminal so often, every time i need to start something. I think there might be some native apps for doing so but i need it to be an online service.

We could have all generators installed and updated from the official repository automatically.

A nice UI to select a generator, see what it's going to produce and select optional features.

some of the most famous builders online would be:
http://www.initializr.com/
http://jqueryui.com/download/
https://puphpet.com/
.
.
.

Anyone?
Thank for your time,
KB

**Comment by JulienCabanes** [comment]
Hi, this is a personal project I'm working on at the moment which looks like what you asked for. I'm thinking about hosting it as a free online service when finished.
https://github.com/JulienCabanes/Yeoman-UI
