### ISSUE TITLE
bookmarklet to give any <textarea> code coloring

### ISSUE THREAD

**Issue by keithwyland** [h5bp/lazyweb-requests#157]
couple cases where sometimes i'm editing code in a plain `<textarea>` on a web page and some code coloring, like from CodeMirror or whatever, would be great.

**Comment by renatomartins** [comment]
http://ajaxorg.github.io/ace/build/demo/bookmarklet/

**Comment by arthurvr** [comment]
> http://ajaxorg.github.io/ace/build/demo/bookmarklet/

Is there anything more outstanding in this issue? Looks like it's built or did we want anything more?

**Comment by keithwyland** [comment]
I haven't found that bookmarlet to work.

However, I no longer need this.
