### ISSUE TITLE
UTF8 Please

### ISSUE THREAD

**Issue by pomeh** [h5bp/lazyweb-requests#160]
Create a website to aggregate all kind of informations about UTF8 encoding.

First of all, a simple presentation ("newbie" friendly) of UTF8, it's advantages and disadvantages over other encoding, what's the BOM...
Then, how to use it correctly: in programming languages (how to handle/convert text with different encodings), in text files, in databases, in web browser, in text editor/IDE and everywhere else.
Finally, how to fix problems with encoding: how to detect which encoding a file uses (for Unix, Mac and Windows users), how to convert files/databases/... from one encoding to UTF8, how to handle it in web applications (in JavaScript, PHP, Python, ...).

I know all those informations are already available on the Web (and on StackOverflow !), but having all this in one single place and in an user friendly website would be just awesome :)

If anyone wants to hack on it or know an alternative just let me know :)

**Comment by stuartpb** [comment]
http://www.joelonsoftware.com/articles/Unicode.html does a pretty good job of covering it imho.

**Comment by roblarsen** [comment]
>http://www.joelonsoftware.com/articles/Unicode.html does a pretty good job of covering it imho.

Still going strong.
