### ISSUE TITLE
Domain parking for developers

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#167]
I have tons of domains I've grabbed for projects I'm planning to tackle at a hackathon down the line or something like that. My registrar sets me up with an initial "parking page" for that domain, but it's oriented toward being a damned dirty domain squatter/scalper: just regurgitated search results polluted with  referral schemes and links to "BUY THIS DOMAIN NOW".

I don't *want* that on my unused domains. What I want is a page that would give a description like the one I'd make on GitHub when I create the repo, a place for interested devs to contact me about getting the project started, a "notify me when this actually gets made" mailing list signup, things like that.

**Comment by jgheaton** [comment]
Sounds like a great idea! So it'd be more specific than an "under construction" kind of page. Would is specifically be for hackathons/open source stuff? I'm thinking for copy purposes.

**Comment by stuartpb** [comment]
Why was this closed?

**Comment by Garbee** [comment]
I'd bet it was closed because there are plenty of domain parking pages around. Also, anything with a signup form should be catered to what is going on and non-generic. Seems slightly out-of-scope for lazyweb.

**Comment by paulirish** [comment]
It's out of scope for lazyweb-requests yes.

It looks like this is close-ish, btw.
https://github.com/scripting/pagepark

**Comment by stuartpb** [comment]
pagepark.io isn't what I'm looking for - that's just a template for a Node server layout that uses directories for virtual hosts. Using it still requires you to clone the repo, set up a hosting environment, write/design HTML pages for each site, and commit/push/redeploy for each site you're running - it's basically as much work as setting up an MVP.

What I want is something that requires *zero* effort beyond the actual registration of the domain- an existing CNAME to init the www record to, that will serve a tasteful "Coming soon" page instead of a tacky, embarrassing "MAKE $$$$ WITH WEB SITE N0W!!1" abyss.

I've started work on this, as [Parked Project](https://www.parkedproject.com/) (https://github.com/parkedproject/parkedproject.com) - right now, there's no detail beyond the initial "Coming soon" template (which is also being applied to parkedproject.com itself). Going forward, I plan to implement some kind of user accounts system (probably just deferring to GitHub at first), accessible from https://www.parkedproject.com/, that will provide the console for configuration / adding more information to the template. (I plan to have the server check DNS records to verify ownership: https://github.com/parkedproject/parkedproject.com/issues/1)
