### ISSUE TITLE
Dictionary of Reserved Words

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#168]
I'd like to build a more robust site around this idea I initially had at https://gist.github.com/stuartpb/5710271 :

> A general list of words you may want to consider reserving, in a system where users can pick any name, in a context where the system may use names as well.
> 
> One prominent example of a system where this is the case would be a site that serves pages for users, at their username, from the site root, like http://twitter.com/stuartpb . In this system, you would want to reserve some routes for pages that would commonly be expected to have certain content, such as http://twitter.com/about

I'd like to do this with something like a gh-pages/Jekyll blog with an entry for each word, explaining why you might want to reserve it, and categories for each entry for which kinds of words you might want to reserve (like the headings in this file).

**Comment by paulirish** [comment]
https://github.com/shouldbee/reserved-usernames  yah?


seems to be the maintained extension of these

* https://gist.github.com/mahemoff/2314663
* https://gist.github.com/caseyohara/1453705

**Comment by stuartpb** [comment]
Okay, I've started compiling the data I want at https://github.com/opensets/reserved-words - it's joing to be like an incredibly dry version of the Jargon File, explaining where certain words are used

Also, my advice to everybody who wants to be cautious about reserving words and is saying these lists should include any word they can think of is to download [SCOWL](http://wordlist.aspell.net/scowl-readme/) and just add everything on every wordlist that matches your allowed character pattern, There, problem solved (except for the way you're now disallowing registration for brands like Apple or users like @substack).

**Comment by stuartpb** [comment]
Also, my advice to everybody who wants to be zealous about reserving words, saying these lists aren't comprehensive enough and should include any word they can think of regardless of scope, while simultaneously asserting they don't need any kind of metadata or categorization, is to download [SCOWL](http://wordlist.aspell.net/scowl-readme/), reserve every line in every list (with any non-word characters removed), then check potential names against this list after applying the same removal of non-word characters to them and any other existing names in the system (and maybe even further normalization of similar-looking characters like `i` and `l` and `1` - that's what Gmail does). While you're at it, throw in a minimum-length restriction to lock out any two-or-three-letter country code identifiers.

There, problem solved - except for the way you're now disallowing registration for brands like Apple, or users like @substack, or *anybody* who wants to use their first or last name or initials. Meanwhile, users can still phish by registering names like `googlesecurity` because you're only doing word-matching to avoid the Scunthorpe Problem and you're treating all words as equal.

**Comment by stuartpb** [comment]
Also, the secondary advantage of this dictionary is it provides a place to look for inspiration when designing a vocabulary for routes (so one can compare their projected usage to how other sites have used the same word, and maybe take a note from the challenges their design faces).
