### ISSUE TITLE
XHR Event polyfill

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#169]
(crossposted from inexorabletash/polyfill#49)

XMLHttpRequest, in the latest specs and browsers, supports more events than "readystatechange" (namely "error", "abort", "timeout", and "load"), and supports adding listeners using addEventListener rather than just setting the "onreadystatechange" property: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Events

It would be nice if web developers could have a polyfill that allows us to rely on the presence of these events and not worry about our code breaking on IE9.

**Comment by cvrebert** [comment]
(from the other thread:)

> `@inexorabletash`:
> XHR's a dead end anyway. [fetch()](https://fetch.spec.whatwg.org/#fetch-api) is the new hotness.

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.

**Comment by drdamour** [comment]
this stale bot is working well

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
.
