### ISSUE TITLE
Screenshot / Screenshare sharing to URL

### ISSUE THREAD

**Issue by paulirish** [h5bp/lazyweb-requests#170]
There's www.getcloudapp.com, www.cloudup.com, www.gyazo.com, www.imgur.com, and www.gfycat.com. All [are great](http://www.paulirish.com/2009/get-gyazo-for-seriously-instant-screen-grabbing/) but I am thinking of something slightly better …
### Requirements:
- **Quick capture**: short time from capturing the screen to URL automatically in clipboard
  - capture is done by running/triggering an application instead of hijacking all cmd-ctrl-shift-4's, for privacy.
- **Custom domain**: something with more identify than `cl.ly`. 
  - ideally files are hosted on your own server, but hosting elsewhere OK given easy delete ability
- **Video screencapture support**
  - it's transcoded to a gifv/gfy. Mostly viewed as webm/mp4 but a pure animated gif fallback is available.
- **[twitter card support](https://dev.twitter.com/cards/types/photo)** for nice embedding (both for image & video)
- **open source**
  - however maybe using gfycat or imgur APIs for video -> gifv/gfy conversion
### Projects that are quite close…:
1. @jomo's [imgur-screenshot](https://github.com/jomo/imgur-screenshot) bash script. 
   - most of this except video support
2. @ralphholzmann's [grabs](https://github.com/ralphholzmann/grabs) node app
   - self-hosting, twitter card support, gyazo for capture, but no video
3. some parts of the @gyazo clients/server [are open source](https://github.com/gyazo/)

**Comment by arthurvr** [comment]
OH yeah. I'm in.

**Comment by stuartpb** [comment]
I was thinking the other day about how I really want an open-source Chrome extension for capturing within tabs (the Chrome Store has a few capture extensions listed, but they all feel kinda shady and have no source you can view).

**Comment by stuartpb** [comment]
server-side, can't the video/gif conversion just be done via ffmpeg (the imagemagick of video)?

**Comment by uiureo** [comment]
Did you check out licecap?  It's a gif screencapture tool and open source.

https://github.com/lepht/licecap

**Comment by meat147** [comment]
there is sharex wich can satisfy your request except the twitter thing i think.

**Comment by stuartpb** [comment]
I just realized that, for within Chrome, this is actually really simple, using https://developer.chrome.com/extensions/tabs#method-captureVisibleTab. Not sure if its perf is suitable for video, though.

**Comment by jomo** [comment]
@stuartpb fyi, Firefox also has this feature [in their GCLI](https://developer.mozilla.org/en-US/docs/Tools/GCLI). I'm sure it can be accessed by extensions in some way, too.

**Comment by stuartpb** [comment]
@paulirish @arthurvr What's the minimum framerate for this you would consider acceptable?

**Comment by paulirish** [comment]
10fps recording would be OK.
24fps would be acceptable.
and 60fps would be ideal, considering the output format is a <video>

**Comment by Efreak** [comment]
Given that you're mentioning bash, I'm guessing that [ShareX](https://github.com/ShareX/ShareX) isn't any good for you?

Several open source linux-only programs that don't do everything you want:
- [shutter](http://shutter-project.org/) doesn't do videos that I know of, has an open plugin API
- [Kazam Screencaster](https://launchpad.net/kazam), looks like it only supports vp8/webm, no uploading
- [SimpleScreenRecorder](http://www.maartenbaert.be/simplescreenrecorder/#what-is-simplescreenrecorder) also has support for recording opengl, no uploading

Some points:
- Using imgur/giphy for conversion is a good idea, but it should be able to fall back on local binaries if necessary--some of us don't have the necessary bandwidth, and others don't have the necessary processing power. And given a program like this, I think it would be ideal if the server was entirely optional
- I don't know much about linux key-capture applications, but hotkeys should either be an option, or there should be an obvious example of using another application to set up hotkeys.
- ffmpeg actually has screen capture functions built-in. I'm not sure of the performance, but I'd imagine that most other programs would just rely on it anyways. gstreamer and vlc can also both do this. I'm not sure if there's any way to capture sound as well as video from the desktop. If you want to be platform-independent, ffmpeg and vlc should both work on mac/windows as well.

@stuartpb imagemagick can actually transcode video to gif, although it still depends on ffmpeg.

**Comment by stuartpb** [comment]
I just realized Chrome has also had https://developer.chrome.com/extensions/tabCapture for like a year, though it seems like the problem is in capturing the video stream (it might be *slightly* more performant than repeatedly requesting the page as PNG DataURL).

**Comment by auchenberg** [comment]
Instead of doing a continous a tapCapture, you might be able to use the ``chrome.debugger`` API from the extension to start Chrome's Screencasting feature, which emits BASE64 encoded PNG's over the remote debugging protocol. See https://chromedevtools.github.io/debugger-protocol-viewer/Page/#method-startScreencast

I don't know the implementation details, but I might get you a higher frame-rate.

**Comment by styfle** [comment]
I started working on a [screen recording app](https://github.com/styfle/magnemite) built with Electron, but the use case is a little different than just grab and upload. The part I haven't figured out yet is how to get the video off the end-user's computer so I'll have to check out the source code in some of those links above.

**Comment by grayghostvisuals** [comment]
@paulirish Might be useful to reach out to Kap since it's Open Source, built with Web technology and already on GitHub https://github.com/wulkano/kap.

**Comment by gariasf** [comment]
I'd plus on using ShareX to take a screenshot. The good thing about it is that it allows for custom uploaders.
A friend and I are building an app that'll allow people to self host a media sharing service, including uploading images via curl or ShareX.

You can take a look, still in development:
client: https://github.com/nethruster/nethloader-frontend
server: https://github.com/nethruster/nethloader-backend

**Comment by acant** [comment]
[Firefox](https://www.mozilla.org/en-US/firefox/new/), as of version 55, is now shipping with [Firefox Screenshots](https://screenshots.firefox.com/) which can do screenshots in the browser and push them to the Mozilla service.

The code for the server and the WebExtension is available here:
https://github.com/mozilla-services/screenshots

**Comment by styfle** [comment]
If you don't want to install anything and your website is public, you can take a screenshot with [screenshot-v2.now.sh](https://screenshot-v2.now.sh).

If you are interested in twitter cards, see [og-image.now.sh](https://og-image.now.sh) which is open source so you can [fork your own image generator](https://github.com/styfle/og-image).
