### ISSUE TITLE
Universal Domain Registrar Dashboard

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#171]
One thing that people have been discussing today, now that Google is entering the domain registration game, is that the state of management interfaces provided by most domain registrars is, on average, _miserable_ - cPanel at best.

I was thinking: it would be interesting if somebody could hack something with userscripts that gives _any_ registrar an interface like Google's, or even something for managing _multiple_ registrars. (I've resorted to a series of lists on Trello for managing which domains I have registered with which companies, based on pricing from [domcomp](https://domcomp.com).

**Comment by septianw** [comment]
i've diagramming the idea like this before.
