### ISSUE TITLE
schema.json

### ISSUE THREAD

**Issue by AaronLayton** [h5bp/lazyweb-requests#172]
I am not sure if this exists, it is just a thought that has popped into my head and figured I would write it down whilst I remember.

I think it would be useful to be able to include a `schema.json` file on any given page that would act exactly the same as, and unify the different standards **Microdata**, **Microformats**, **RDF's**. 

`note: I just checked Schema.org and there is a JSON-ld format now - aces!!`

The second part to this would be to include it as a link as so

``` html
<link rel="schema" href="schema.json">
```

This could then keep the page size to a minimum as a visitor never needs to know this information so why force them to download it in the first place. 

``` html
<script type="application/ld+json"> { ... } </script>
```

The browsers can ignore the file and search engines can then pick this up instead. The format would be exactly as set out by schema.org.

``` json
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "Miami Heat at Philadelphia 76ers - Game 3 (Home Game 1)",
  "location": {
    "@type": "Place",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Philadelphia",
      "addressRegion": "PA"
    },
    "url": "wells-fargo-center.html"
  },
  "offers": {
    "@type": "AggregateOffer",
    "lowPrice": "$35",
    "offerCount": "1938"
  },
  "startDate": "2016-04-21T20:00",
  "url": "nba-miami-philidelphia-game3.html"
}
```

Is this something that would be good?

**Comment by jonathan-fielding** [comment]
That makes complete sense and would stop us spamming the browsers with stuff they don't care about

**Comment by AaronLayton** [comment]
Maybe @paulirish knows anyone working on the Schema website / specs?

**Comment by paulirish** [comment]
@danbri is a great guy for this.

**Comment by danbri** [comment]
Maybe rel=meta ?

http://microformats.org/wiki/rel-meta
