### ISSUE TITLE
es6please.com?

### ISSUE THREAD

**Issue by tIppl5** [h5bp/lazyweb-requests#173]
Looks like a nice idea. io.js, node, and some browsers start to implement stuff so perfect time to start building that out. Don't know if it's something for h5bp org or not? What do @paulirish @nimbupani @arthurvr @mathiasbynens and @alrra think?

**Comment by mathiasbynens** [comment]
There’s already [a lot of resources on ES6/ES2015](http://addyosmani.com/blog/ecmascript-6-resources-for-the-curious-javascripter/) and I’m not sure we need another one.

**Comment by derek** [comment]
Partially true, because there's always room for more.  The distinction is that it should be new content.  If it's just more of the same, then it's probably unnecessary.

**Comment by Garbee** [comment]
There wouldn't really be any new content. Things like the [compat table](http://kangax.github.com/es5-compat-table/es6/) are already very detailed resources. Doing yet another thing would be inferior except perhaps in UI.  If people are already tracking this stuff in good manner, why create yet another thing and duplicate effort for no real gain? If anything register es6please and forward to the compat table.
