### ISSUE TITLE
Screenshort extension

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#176]
It would be cool if there was a Chrome extension that automatically generated an image based on highlighted text and opened up a form to post a tweet with it, a la http://oneshot.link/

Here's how I'd like to do it:
- Use innerText (which gets the text that _would be rendered_ to get a certain amount of context (sentences) around the highlighted span.
- Put these spans of text into `<p>` elements (with a `<span>` for the highlight), and put those into a foreignObject in an SVG, then render that SVG to a canvas, then get the PNG data URL from that canvas. (See https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas for how this works.)
- Somehow open the Tweet dialog on Twitter with that PNG as a pre-attached image. (It seems this is the tricky part, without a server-side app doing the tweeting.)

**Comment by Efreak** [comment]
Twitter should not be the only option for something like this, that would be rather limiting. Instead, allow *any* type of website, customizable like [ShareX](http://i.imgur.com/reUvZHE.png) is.

**Comment by stuartpb** [comment]
Maybe, but the need for this is most pressing on Twitter - other sites don't have a 140-character limit that keeps you from including quotes of significant length.

**Comment by Efreak** [comment]
Also, you might consider using textContent or wholeText vs just innerText. innerText only works on a single element, while textContent will work on child nodes and wholeText will work on ["logically adjacent nodes"](https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText).

You should be able to use twitter's api with an xmlhttptrequest to upload the base64-encoded image to their api via a [media/upload](https://dev.twitter.com/rest/reference/post/media/upload), then add the media_id to another request to [statuses/update](https://dev.twitter.com/rest/reference/post/statuses/update).

**Comment by stuartpb** [comment]
Yeah, but making a request to their API would require embedding the app's secret key into the extension, wouldn't it? Also, sending the tweet via API would preclude using Twitter's tweet composition UI.

**Comment by ankurkaushal** [comment]
I made an extension on similar lines called [Snipmark](https://chrome.google.com/webstore/detail/snipmark/ihigmckhplkfliiahaeolehebjehlojp) which essentially let's the user select the text and have it generate a gist. I think we can add call the API via our own backend which I believe would be more secure.

**Comment by roshanrathod** [comment]
[Lightshot (screenshot tool)](https://chrome.google.com/webstore/detail/lightshot-screenshot-tool/mbniclmhobmnbdlbpiphghaielnnpgdp?hl=en) has selection and sharing option. Is that what you are talking about?
