### ISSUE TITLE
A proper DeviceMotion/DeviceOrientation polyfill

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#177]
There's nothing out there that _actually polyfills_ (and fixes values for) the DeviceMotion API. There are a few libraries that implement their own API (gyronorm, gyro.js, FullTilt) or emulate the interface (remy's), but nothing that _takes an existing API for device motion and translates it into the standard API_. Moreover, there's _nothing_ out there that translates from the Cordova [`navigator.accelerometer`](http://docs.phonegap.com/en/edge/cordova_accelerometer_accelerometer.md.html) or [`navigator.compass`](http://docs.phonegap.com/en/edge/cordova_compass_compass.md.html#Compass) APIs.

**Comment by CrowdHailer** [comment]
I think this would be great. If we can start creating a collection of resources I might be able to look into this in a few weeks. I have been creating a website which would use this. Currently I am forging ahead to make it work for android only but when I get a bit more time would keenly contribute to working on this.

**Comment by CrowdHailer** [comment]
@stuartpb Do you have a link to the "remy's" interface. I have found the first three librarys but not the last one

**Comment by stuartpb** [comment]
Remy's doesn't really matter, IIRC it's for machines that don't have the sensors at all.

**Comment by stuartpb** [comment]
@substack do you think you might be able to implement this, tapping into your deep, knowledgeable understanding of [balls](http://substack.neocities.org/balls.html)?
