### ISSUE TITLE
List of popular jQuery plugins and their Vanilla JS equivalents

### ISSUE THREAD

**Issue by LeaVerou** [h5bp/lazyweb-requests#178]
There is http://youmightnotneedjquery.com/ but many people don’t use jQuery because of jQuery itself, but because of the crapload of popular libraries that require it. It would be great if someone built a list of such popular scripts and their Vanilla JS equivalents (there is a wealth of scripts these days not requiring jQuery). Only a few to begin with should be sufficient, then the community can complete the list via PR.

**Comment by voxpelli** [comment]
+1 on this.

A start would be to find the popular jQuery plugins. Are there any such lists? One I can think of is http://www.unheap.com/, but its a list of _good_ rather than _popular_ plugins.

**Comment by voxpelli** [comment]
@davidyezsetz started building a list at: https://github.com/davidyezsetz/you-might-not-need-jquery-plugins

**Comment by voxpelli** [comment]
@madrobby says that http://microjs.com/ can easily be extended with such information: https://twitter.com/thomasfuchs/status/590112933457309696

Repository for microjs.com: https://github.com/madrobby/microjs.com

**Comment by davidyezsetz** [comment]
@LeaVerou @voxpelli I'll keep throwing in some of the plugins I use, but there are actually very few that I use on a regular basis so feel free to add. Also if you have suggestions concerning structure, I'm all ears.

**Comment by davidyezsetz** [comment]
@voxpelli @madrobby microjs would make sense if the list only includes small plugins. Either way the first step would  be to compile a list. I'll dig through http://www.jqueryscript.net/popular/ & the likes to compile a basic list and then start looking for alternatives.

**Comment by stuartpb** [comment]
I just came across http://callmecavs.github.io/layzr.js/ which appears to be a vanilla alternative to jQuery Unveil.

**Comment by LeaVerou** [comment]
For sortable functionality: http://bevacqua.github.io/dragula/ and https://github.com/RubaXa/Sortable

**Comment by davidyezsetz** [comment]
In accordance with youmightnotneedjquery.com I think it might be a good idea to add a support column (e.g. ie8, ie9) to have the option to filter for that later on. Any objections?

**Comment by davidyezsetz** [comment]
@stuartpb @LeaVerou I added all three.

**Comment by davidyezsetz** [comment]
I pushed in a basic github page: http://davidyezsetz.github.io/you-might-not-need-jquery-plugins/
I will add filtering and at least a bit of design later. It would be important to actually get a good amount of data though.

**Comment by davidyezsetz** [comment]
Searching & filtering is implemented now. More plugins can be added to the list via issues or a markdown file as a pull request

**Comment by LeaVerou** [comment]
Guys, this is nice but the whole idea was to have a directory of correspondences of vanillaJS libraries to popular jQuery plugins. Right now it’s just a directory of vanillaJS libraries, with no information about which jQuery plugins they correspond to. Apart from that, nice work though!

**Comment by davidyezsetz** [comment]
@LeaVerou I've added the attribute "replaces" to the entries and made it filterable. I'll update the data throughout the day.

The list still is a wee bit short, so it would be great if more data would be submitted.

**Comment by thednp** [comment]
LOL
https://github.com/thednp/bootstrap.native

**Comment by ThibaultJanBeyer** [comment]
jQuery UI for drag & drop: https://jqueryui.com/draggable/ & https://jqueryui.com/droppable/
Alternative: https://github.com/ThibaultJanBeyer/dragNdrop/

**Comment by danny007in** [comment]
Any alternative for datatable

**Comment by ThibaultJanBeyer** [comment]
Query UI for selections: https://jqueryui.com/selectable/
Alternative: https://github.com/ThibaultJanBeyer/DragSelect
