### ISSUE TITLE
a11y widget markup cheat sheet

### ISSUE THREAD

**Issue by Munter** [h5bp/lazyweb-requests#179]
Like many other people I know far to little about how html semantics and aria tags work with screen readers. I can read the HTML5 and Aria specs, but it's very hard to figure out what the best practices are, especially in a world where getting your hands on the tools is hard, you're not properly trained to use them etc.

I wish there would be a central repository with a cheat sheet with example markup for all sorts of widgets and standard markup patterns where I could just copy/paste them into my markup, Angular directive, Knockout custom binding, Web Component, React component or whatever.

Things I can remember right now that I have been in doubt about or currently have nu clue how to mark up properly:
- Modals
- Buttons with dropdowns
- Autosuggesting filtering input
- Tabs
- Help text balloons
- Balloons with actual interactivity
- How do I skip the screen reader directly to the content
- Tables

I bet we can collectively come up with more things that would be nice to have a definitive best practice on that people could just copy/paste. Because we know they're unlikely to learn all the specs by heart and figure out the best practices on their own

**Comment by grayghostvisuals** [comment]
Suggestion: You should submit this to the [A11YProject](https://github.com/a11yproject/a11yproject.com) to be included in the [patterns section](http://a11yproject.com/patterns) FWIW.

**Comment by paulirish** [comment]
Good call, @Munter. 

Just recently I was talking with @alice about this as well.. https://w3c.github.io/aria-in-html/ is fairly decent, but could be improved.

Also think such a resource would make sense to end up living in a11yproject.

**Comment by davidyezsetz** [comment]
I think that almost all of these are covered in the [a11y project - pattern section](http://a11yproject.com/patterns/)

**Comment by niksy** [comment]
This is an excellent idea!

[Practical ARIA examples](http://heydonworks.com/practical_aria_examples/) by Heydon Pickering and [OpenAjax Accessibility examples](http://oaa-accessibility.org/examples/) are two resources I’ve found highly valuable for real word usage examples. [Easy ARIA tips articles](https://www.marcozehe.de/?s=easy+aria+tip) by Marco Zehe are also helpful.

Does anyone think that this should be suggested to A11YProject?

**Comment by grayghostvisuals** [comment]
Pinging @davatron5000

**Comment by davatron5000** [comment]
Hi there! I'm Dave from the @a11yproject. We'd be happy to host this conversation but the solution (as people have mentioned) maybe exists in the A11Y Pattern Library http://a11yproject.com/patterns/

Unfortunately, Accessibility is such a nuanced field that a bunch of copy-pasta may actually make things less accessible if used incorrectly. My favorite example of this is `alt` text. Everyone says "Must use `alt` text", but if it's redundant text, it's actually less usable. The shortest we could get an article on how to use `alt` text was ~300 words. http://a11yproject.com/posts/alt-text/

Anyways, we're trying to make things more digestible and get it to the point where any developer can quickly build a working knowledge of Accessibility.
