### ISSUE TITLE
DOM template engine with "updaters".

### ISSUE THREAD

**Issue by elfet** [h5bp/lazyweb-requests#180]
Hi guys! 
Now i'm working of DOM template engine (a view). 
Main idea is construct DOM API js calls from html template. I know where are a lot of such libs, my differ in next:
- really small (<1kb)
- server compiled templates
- no dependencies
- autogenerated update method, so you do not need work with DOM directly.

There is no documentation yet. Take a look at example:

``` html
<div>
    <span>{{ hello }}</span>
    <span>{{ world }}</span>
</div>
```

will generate code:

``` js
{
    "test": function () {
      // Create elements
      var div0 = document.createElement('div'),
        span1 = document.createElement('span'),
        text2 = document.createTextNode(""),
        span3 = document.createElement('span'),
        text4 = document.createTextNode("");

      // Construct dom
      span1.appendChild(text2);
      span3.appendChild(text4);
      div0.appendChild(span1);
      div0.appendChild(span3);

      // Create setters
      var set = {
        hello: function (value) {
          text2.nodeValue = value;
        },
        world: function (value) {
          text4.nodeValue = value;
        }
      };
      // Create view
      var view = {
        update: function (data) {
          var t;
          (t = data.hello) !== undefined && set.hello(t);
          (t = data.world) !== undefined && set.world(t)
        }
      };

      // Set root nodes
      view.nodes = [div0];
      return view;
    }
  });
}
```

And you can use it like this:

``` js
var view = monkberry.render('test');
view.appendTo(document.getElementById('root'));
...
view.update({hello: 'Hello', world: 'world!'});
```

What you think :grey_question: :grey_question: :grey_question: 
Here is it: https://github.com/monkberry/monkberry/

**Comment by Garbee** [comment]
I'm not sure fostering yet-another-js-template-engine is in the scope of this area. We should focus on fostering new ideas that push the web forward, not another rendition on things that already exist.

**Comment by arthurvr** [comment]
Totally agreed with @Garbee.

**Comment by elfet** [comment]
And what are you thinking about inline styles what will be cut out to separate css file?
