### ISSUE TITLE
Make npm run scripts less noisy

### ISSUE THREAD

**Issue by ngryman** [h5bp/lazyweb-requests#183]
Hey guys,

If you use `npm` as a build tool, you probably are annoyed by the default verbose log level. People are starting to complain about this, but it seems that nothing really happens.
I opened an issue with more details. If you feel like me, please :+1: / add your suggestions.

Here is the issue: https://github.com/npm/npm/issues/8821.

Thanks!

**Comment by styfle** [comment]
Looks like it was closed in https://github.com/npm/npm/commit/65b9943e9424c67547b0029f02b0258e35ba7d26

**Comment by paulirish** [comment]
Yup fixed here: https://github.com/npm/npm/commit/65b9943e9424c67547b0029f02b0258e35ba7d26

Also yarn doesn't have this problem.

closing!
