### ISSUE TITLE
Help/educate users about malicious/ads injecting addons they might have installed

### ISSUE THREAD

**Issue by xPaw** [h5bp/lazyweb-requests#188]
I've recently started tracking javascript errors on my website, and surprisingly a lot of the errors logged are related to malicious addons that inject ads and other unwanted crap. Some of them simply fail because I use CSP and disallow iframes/evals.

Most (if not all) of these addons directly inject scripts into the page, so it should be possible to detect them. Some look like chrome extensions that are installed by malware on the PCs.

**Comment by Zearin** [comment]
:+1: 

I am uncomfortable with the current state of ads on the web.  I realize it’s an arms race, but the ads seem to have the upper hand from where I sit.  They are getting sneakier and more insidious than ever.

**Comment by fega** [comment]
I like the idea too..
