### ISSUE TITLE
Build web app to provide an overview of browsers stats (caniuse.com style)

### ISSUE THREAD

**Issue by auchenberg** [h5bp/lazyweb-requests#189]
**NEED**: An overview of browser stats from multiple vendors like StatsCounter

**WHY**: Currently it's too hard to gather a combined overview from today's browser stats. The [caniuse Usage table](http://caniuse.com/usage-table) are great, but is only relying on data from StatsCounter. 

**HOW**: Build a simple app that plots browser stats from the different vendors into the same graph, and with filtering options to filter by vendor/browser/version. Maybe put it on browserstats.io? Much inspiration from CanIUse

**APIs**: 
http://api.statcounter.com/docs/v3
http://www.w3schools.com/browsers/browsers_stats.asp
http://www.w3counter.com/globalstats.php
Google Analytics?
Google?
Bing?

**Comment by AaronLayton** [comment]
Would be awesome if Google could provide data on this from their homepage usage?

Not actual amounts but just percentage stats etc

**Comment by scheinercc** [comment]
+1, but I would advice against from adding w3school into the list as they state themself on the stats page "W3Schools is a website for people with an interest for web technologies" which means it's a rather specific audience and those numbers therefore clearly biased.

**Comment by roblarsen** [comment]
Google's data would be biased towards Chrome, Yahoo's to Firefox/Chome and Bing/MSN to IE. You'd want to stay away from any stats that are a byproduct of the the default search engine game. 

Maybe if we could get all three (+ Yandex, Baidu and other regional powerhouses) the combination would be properly representative. Search engines would miss out on in-app browsers though...

**Comment by AaronLayton** [comment]
@roblarsen not sure how true that would be, alot of people use Google as their homepage, regardless of the browser. While I'm sure your right that Yahoo would see a bit more FF as its their default, I'm not sure it would be that much? Would be interesting to find out though.

If not the Google homepage then maybe we look at the Alexa top 100 and see if there is a site in there more suited that could provide data? (if that's even possible)

**Comment by roblarsen** [comment]
@AaronLayton There's a reason all these places fight over defaults. It definitely skews the data:

http://www.winbeta.org/news/yahoo-sees-increase-search-traffic-after-they-become-default-firefox-34

Most users don't change defaults. 

http://www.theguardian.com/technology/2013/dec/01/default-settings-change-phones-computers

**Comment by roblarsen** [comment]
Additionally, there's also no single site that would do it anyway. Emphasis on World in WWW. 

Even if Google weren't skewed to Chrome/Android browser it would lose out on China. You could say Amazon, but that's not representative of China, either. You could say Amazon + Taobao, but then what about, say, Russia or India? 

The best source of the data would be a service like Google Analytics or AdWords that's not blocked in China and is on billions of pages.
