### ISSUE TITLE
Data model for Javascript

### ISSUE THREAD

**Issue by rajzshkr** [h5bp/lazyweb-requests#190]
I am planning to build a lightweight data model for javascript.
Does anyone join with me?
https://github.com/rajzshkr/js-data-model

initial cut is available here

**Comment by AaronLayton** [comment]
Just taken a look, I see what your doing there. How much of this can already be achieved with just the built in functionality of JS? Could you provide some examples

**Comment by rajzshkr** [comment]
we can achive many thing with build in js function. But i am trying to build a model with all features in one place. I will do some example and will update here shortly.

**Comment by sergiottomas** [comment]
you might create more information of this project?

**Comment by sergiottomas** [comment]
Your project is very cool Rajz, I can contributed?
