### ISSUE TITLE
source for finding reserved words for any (most?) languages in one place

### ISSUE THREAD

**Issue by karlgroves** [h5bp/lazyweb-requests#191]

**Comment by AaronLayton** [comment]
It seems like there should already be something like this available somewhere.

**But if not...**

##### Source languages
There are lots of projects on here that could be used as a good starting point. We could select the top languages now maybe something like [this](http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html)

* Java
* C
* C++
* C#
* Python
* PHP
* Visual Basic .NET
* JavaScript
* Assembly language
* Ruby
* Perl
* Delphi/Object Pascal
* Visual Basic
* Swift
* MATLAB
* Pascal
* Groovy
* Objective-C
* R
* PL/SQL

#### Data
How are you think this gets stored or consumed? Storing it in a repo as JSON data for each language seems like a good idea.

#### Consumption
The JSON files could be used by a simple site hosted on gh-pages branch

**Comment by stuartpb** [comment]
#168

https://github.com/opensets/reserved-words - I've been working on this for a while, I'll go ahead and make the first commit in a little bit.
