### ISSUE TITLE
JS minifier for arrays / objects with repeated values

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/lazyweb-requests#193]
Wanted: a JS library / npm module that minifies code like:

```js
['long string', 'long string', 'long string']
```

…into something like…

```js
var a='long string';[a,a,a]
```

I’m asking this here because I feel like this probably exists already and I just don’t know about it.

**Update:** I know about gzip compression and how it works, peeps. I’m not trying to optimize for download size/time but rather for storage space. My specific use case is https://github.com/mathiasbynens/node-unicode-data/issues/27.

**Comment by hzoo** [comment]
Responded on twitter - https://twitter.com/left_pad/status/734201571832156160

Kind of overkill since it's not a standalone module, but I hacked up http://astexplorer.net/#/i3zwFKJWDC

<img width="925" alt="screen shot 2016-05-21 at 9 57 22 pm" src="https://cloud.githubusercontent.com/assets/588473/15451704/7bc29e90-1f9f-11e6-8a2f-ee35f2897a0d.png">

Which seems to work on ^, but probably not performant, etc.

**Comment by mikesherov** [comment]
One thing to consider with minifications like this, that once passed through gzip, the benefit disappears or is actually detrimental. Even the example code is 39 bytes "unminified", and 46 bytes "minified". 

The gzip algo eats long repeated strings for breakfast.

**Comment by hzoo** [comment]
Yeah that makes sense.

https://twitter.com/mathias/status/734172468215185412

But it looks like @mathiasbynens' usecase is to save hard drive space?

**Comment by mikesherov** [comment]
You can still gzip things and store them on a hard drive. :-)

**Comment by benjamn** [comment]
If you're willing to run a decoder, https://github.com/benjamn/arson encodes/decodes this kind of data pretty well:
```js
> arson = require("arson");
{ registerType: [Function],
  stringify: [Function: encode],
  encode: [Function: encode],
  parse: [Function: decode],
  decode: [Function: decode] }
> s = "long string"
'long string'
> arson.encode([s, s, s])
'[[1,1,1],"long string"]'
> arson.decode(_)
[ 'long string', 'long string', 'long string' ]
```

**Comment by mathiasbynens** [comment]
Thanks for the suggestions, everyone!

I’m going to use https://github.com/hzoo/babel-plugin-dedupe-string-literals since I’d rather not perform any run-time decoding.

**Comment by mathiasbynens** [comment]
There’s also <https://qfox.github.io/drew/src/web/web.html> by @qfox. Choose the “For Mathias” preset and click “Load and Go” :)

**Comment by mathiasbynens** [comment]
FWIW, I ended up inlining the gzipped version of the JSON-formatted data: https://github.com/mathiasbynens/node-unicode-data/blob/ed81c895611415950a87af30732dc02a2120373a/scripts/utils.js#L10-L17

Example output: https://github.com/mathiasbynens/unicode-8.0.0/blob/89b412d8a71ecca9ed593d9e9fa073ab64acfebe/General_Category/index.js
