### ISSUE TITLE
Homebrew formula for libwebp (incl. gif2webp)

### ISSUE THREAD

**Issue by mathiasbynens** [h5bp/lazyweb-requests#196]
There is a `webp` formula on Homebrew, but it doesn’t install `gif2webp`.

Let’s create one named `libwebp` that installs all the binaries that come with it.

https://developers.google.com/speed/webp/docs/precompiled points to https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html which contains `libwebp-0.5.0-mac-10.9.tar.gz` which, after extracting, offers the following binaries in `libwebp-0.5.0-mac-10.9/bin`:
- `anim_diff`
- `cwebp`
- `dwebp`
- `gif2webp`
- `vwebp`
- `webpmux`

**Comment by kybradeck** [comment]
Just had a bit of a headache trying to install `gif2webp` this morning. Would be great to include this as part of the Homebrew install!

**Comment by pepelsbey** [comment]
Yes please!

**Comment by gajus** [comment]
Was this ever added?
