### ISSUE TITLE
Browser-based Inkscape alternative

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#197]
It's pretty embarrassing that, when I'm on my Chromebook, I can't robustly edit/produce SVG documents, despite the way that every Summer of Code effort put toward Inkscape's codebase for the last three years seems to have been based on re-implementing things that have been solved problems in Chrome for years (like swapping in yet another implementation of parsing and/or rendering).

[SVG-Edit](https://github.com/SVG-Edit/svgedit) _should_ be capable enough to have feature-parity with Inkscape, but instead it lacks even basic features like the ability to edit a path's control points (this appears to be a feature of the select tool that's only presented when first creating a path, for some reason).

**Comment by Efreak** [comment]
It might also be possible to work with inkscape itself in the browser using [Broadway](https://developer.gnome.org/gtk3/stable/gtk-broadway.html) ([here](https://plus.google.com/+AlexanderLarsson/posts/K4zSmRZP3Gr)'s someone running gimp via broadway). And [this](https://www.reddit.com/r/Crouton/comments/2c9v0u/using_crouton_with_broadway_to_run_gtk_apps_in/) appears to be an attempt by @jmaris at allowing you to launch any app on chromebooks via Broadway, but again I can't use it as I don't actually have a chromebook.

**Comment by jmaris** [comment]
Hey :) ! Just to say it's no longer via broadway, but inkscape Can be ran via crouton ! You should give that a go ! There is a repo on my account that allows for running apps with Xiwi and crouton, i should be working on it again soon :)

**Comment by varemenos** [comment]
[Figma](https://www.figma.com) should fit here pretty well
