### ISSUE TITLE
DIY cross-browser bookmark sync?

### ISSUE THREAD

**Issue by Efreak** [h5bp/lazyweb-requests#199]
I would love to see a good open source cross-browser bookmark sync extension that uses your own storage. I use chrome almost exclusively on the desktop, and firefox almost exclusively on mobile (for extensions), and there's really no way to sync my bookmarks between the two. I also on occasion use IE (or more recently, Edge). LastPass (and other services) provide _very_ easy password syncing tools, but nobody seems interested in a secure cross-platform/browser bookmark sync tool without a focus on social networking. With all the browsers adopting WebExtensions now, I feel it should be easier than before.

So far as I know, there is currently no such thing. The two biggest extensions that I know of (XMarks and EverSync) are cross-platform, but both of them have issues and neither supports using your own server to sync. Other services are either windows-specific, aren't free for large bookmark collections, and/or are cloud-based/social bookmark managers.

**[XMarks](https://www.xmarks.com/)**: Using your own server only works with the firefox version, not chrome. They also have [a terrible privacy policy](http://softwarerecs.stackexchange.com/questions/3317/bookmark-sync-tool-between-internet-explorer-firefox-chrome-safari-and-opera#comment6494_3321).

**[EverSync](https://www.everhelper.me/synchronizer.php)**: [_We need to remotely connect to your PC and check the bug. We can't find on our side._](https://getsatisfaction.com/fvd_suite/topics/eversync_initial_sync_action_buttons_disabled_in_firefox?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=12496630#reply_12496630) (an official answer to an issue they link to on the firefox addon page) should be reason enough not to use them. Beyond that, the free version is also limited to 500 private bookmarks.

**Comment by kenodressel** [comment]
Check this out https://github.com/marcelklehr/floccus

**Comment by rpgoldman** [comment]
XMarks is also getting discontinued by the LastPass folks, so even if you like it, it's no longer an option.

**Comment by xoroz** [comment]
xmarks is dead, RIP 1st may 2018. anything similar to it?
