### ISSUE TITLE
WebExtension to check for HSTS headers

### ISSUE THREAD

**Issue by strugee** [h5bp/lazyweb-requests#200]
I spend a fair amount of my time advocating for HTTPS adoption.

I'd like to do the same for advanced stuff like HSTS headers, but checking for those types of things is way more of a hassle than just looking at the first five characters of the URL. It'd be really neat if there was an extension that checked for these headers and put an icon in the address bar or something. Maybe something similar to tos;dr's design, I dunno.

**Comment by styfle** [comment]
You can use [Mozilla Observatory](https://observatory.mozilla.org/) to check for HSTS and many other security-related headers.

You can read more in my blog post here:
https://medium.com/@styfle/security-best-practices-in-2017-cfdf1784c0a2

**Comment by strugee** [comment]
@styfle right, I know about that. (Thank you though!)

There are lots of ways to figure out if something serves HSTS headers. What I want is something where I can see this information at-a-glance (and without switching to a terminal or another webpage).

**Comment by paulirish** [comment]
https://chrome.google.com/webstore/detail/securityheadersio-analyse/hbghndjigmobckggakgcalcfbohgkgog is close but it's not exactly what you're asking for.
