### ISSUE TITLE
macOS and iOS universal music sharer: Quickly share a YouTube version of what’s playing on your device’s native players

### ISSUE THREAD

**Issue by lief** [h5bp/lazyweb-requests#208]
I’m listening to a song in iTunes and want to share the song with friends on the Internet. 

Normally, I search YouTube for the artist name and song title, choose a video of the song, and share that, so that anyone with access to YouTube can listen. It means I don’t have to concern myself with what streaming service they use. They may be using Spotify or Tidal and not want to open a link to Apple Music because they’re not subscribed and don’t want to just to listen to one song. That sort of thing. 

Currently, I’m doing it manually. I open a browser to YouTube and enter the details with my keyboard, then select the best video for the song and share from there. 

I’d like a macOS sharing extension if that would be widely compatible with the apps requested later in this post, and a sharing extension for iOS, that does this for me, to save me time. It has to detect the artist name and song title and send me to a YouTube search results page for that data, in my chosen browser. I can take the sharing from there. No need to choose the video for me. Just a quick redirect from iTunes (etc.) to YouTube results. String in, URL out. Please tell me if I’m making it sound too simple. 

Ideally, it would detect the data when listening in any of the big streaming services – Apple Music, Amazon, Spotify, Tidal. I’d need it for Apple Music/iTunes, if you want me to tell you where to start.

VLC and VOX are other apps people may want it to support. 

I suspect the BeardedSpice crew may have some helpful code in their repository. 

I could help with iconography. It would only need one icon. Maybe we’ll call it Universe.

**Comment by Garbee** [comment]
This repository is more about helping foster ideas that directly benefit the web platform as a whole. This seems to be a very niche desire that only has one connection to the web.

I don't think this issue tracker is the appropriate place to push this. Perhaps someone knows of a similar place for discussing native desktop focused applications?
