### ISSUE TITLE
Clean up this repo

### ISSUE THREAD

**Issue by roblarsen** [h5bp/lazyweb-requests#211]
I love the idea of this repo, so it stays alive, even though it's not that active. 

I also like having a place where people can propose projects to be moved to the h5bp organization.  😍 

That said, I want to clean up the 98 issues that are here.  Yay.

**Comment by AaronLayton** [comment]
I'm up for helping, what do we need to do?

**Comment by roblarsen** [comment]
@AaronLayton I installed stalebot, so basically all of the issues will end up being closed in a week. (nothing here had been updated in < 30 days so the whole repo qualified. ) What I'd like to do (and touching all the issues will help with this since a lot of people just got notified 👋) is to go through over the week to see if there are any good ideas proposed, that have gotten better with age or more useful or simply should be explored further. 

At that point I'll do a Twitter thing saying "hey, we cleaned up this repo, got any new ideas? Check out these old ideas that are still worth exploring." 

So, if you want to help, take a look at the issue queue and link (here) to issues that you think are still valid/interesting/whatever.

**Comment by AaronLayton** [comment]
@roblarsen sounds good, I will run through them all tomorrow then

**Comment by phillip228** [comment]
Help-wanted

**Comment by phillip228** [comment]
I have a bug on my browser

**Comment by pboling** [comment]
Forcing activity seems like to antithesis of lazy...

Just saying, I am not sure if this is the sort of repo where closing issues has any value.

I would argue that this repo is only vibrant when I has a growing list of ideas!

**Comment by AaronLayton** [comment]
Everything is closed anyway now, it makes this project look dead

**Comment by roblarsen** [comment]
This project is for all intents and purposes dead, so it's just not how it looks. It's how it is. There hasn't been any truly new activity in years. I wasn't trying to "force" new activity. I can't force anyone to do anything, but the idea was to just remind people that it was here. 

Of course, it took this issue being updated for me to even remember that it was here so... it's probably time to archive this repo.
