### ISSUE TITLE
`git browse` commands for opening relevant github pages

### ISSUE THREAD

**Issue by paulirish** [h5bp/lazyweb-requests#25]
* `git browse issues` inside a repo opens the issues page for that project
* `git browse` opens the main project page
* `git browse commits` opens /commits/master
* `git browse commits featurebranch` opens /commits/featurebranch

And maybe some syntax to point to the last commit committed.. `git browse commits HEAD^1` or whatever? 

schacon's git-pulls project actually has `git pulls browse 17` which does the pull request side of this. and uses the github API. quite lovely.

https://github.com/schacon/git-pulls/blob/master/lib/git-pulls.rb

http://thechangelog.com/post/2878756980/git-pulls-command-line-tool-for-github-pull-requests

**Comment by paulirish** [comment]
Hub ftw

**Comment by paulirish** [comment]
# `git open`

It works. oh yeah.

https://github.com/paulirish/git-open/

![git open2015-01-24 13_51_18](https://cloud.githubusercontent.com/assets/39191/5889192/244a0b72-a3d0-11e4-8ab9-55fc64228aaa.gif)

**Comment by stuartpb** [comment]
So that's basically the `git browse` command from `hub` pulled out to its own script?

**Comment by paulirish** [comment]
@stuartpb i think its even less sophisticated. This project is only for people that aren't using [gh](https://github.com/jingweno/gh) or hub.
