### ISSUE TITLE
improve design of webchat IRC

### ISSUE THREAD

**Issue by paulirish** [h5bp/lazyweb-requests#31]
I know jQuery, Google, and other groups all use qwebirc, which is the default webchat of the freenode network.

for example: http://webchat.freenode.net/?channels=html5

project hosted here: http://www.qwebirc.org/ and repo here http://hg.qwebirc.org/qwebirc/src

The client **desperately needs UX and IxD and visual design work**. Anyone with design or javascript skills would be a tremendous help.

I'd love to facilitate the work here, working with the project lead and you. 

Comment if you'd be into this.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, try it out to improve Your design, let say as a supplement of Your issue post, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by mestaritonttu** [comment]
The lead developer of this client is now being paid to work on it full-time and it shows: https://github.com/kiwiirc/kiwiirc

You can try the next gen version here: https://kiwiirc.com/nextclient/

In the near future it will have file sharing and all the bells and whistles of a modern chat platform.

**Comment by thedjpetersen** [comment]
Shout was forked and actively being developed here: https://github.com/thelounge/lounge
