### ISSUE TITLE
Offline XHR replay browser extension

### ISSUE THREAD

**Issue by paulirish** [h5bp/lazyweb-requests#52]
general idea: 
- when you go offline, `window.XMLHttpRequest` gets duckpunched with a mock object.
  - could probably use [sinon.js's FakeXMLHttpRequest](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_xml_http_request.js)
- all calls to it are logged and saved in sessionStorage. 
- when you go back online, you have some mechanism available to replay the calls.
  - the original callbacks are fired with the return payload

for a good amount of tabs I currently have open, I feel like this is totally reasonable and would work.

i figure the audience would mostly be developers, but who knows.

I could also imagine site specific hacks, but it'd be tremendously good to have a community of developers offline-enabling sites/apps on their behalf.

**Comment by PolaEdward** [comment]
Just wanted to add another useful use case.
Imagine having a web app that works internally, like ERP, or any system. but it doesn't support DB Sync, Browser DB, etc.

So using such extension would be a life saver, specially if combined with something like PouchDB !
