### ISSUE TITLE
Comprehensive research of contenteditable/execCommand behavior

### ISSUE THREAD

**Issue by atheken** [h5bp/lazyweb-requests#58]
Some work in this area has already been done:

[Quirksmode execCommand](http://www.quirksmode.org/dom/execCommand.html)
[Rangy](http://code.google.com/p/rangy/)

execCommand appears to behave differently in each of the browser implementations.

contenteditable (and nested contenteditables) behave in interesting ways in each of the main browsers.

Consider IE < 8 irrelevant. How does the execCommand behave in IE 8, 9, Chrome, FF, Safari, (maybe Opera).

Is there a way to normalize the behavior of execCommand (in a similar way to how Rangy normalizes the Range and Selection APIs)?

**Comment by paulirish** [comment]
https://github.com/guardian/scribe/blob/master/BROWSERINCONSISTENCIES.md has some.
