### ISSUE TITLE
A standardized framework for building and including Web Audio API instrument/effect "patches"

### ISSUE THREAD

**Issue by mattdiamond** [h5bp/lazyweb-requests#82]
Title sums it up... I'm envisioning a javascript plugin that allows the user to easily include different instruments/effects with a consistent API (e.g. Instrument objects with Play methods that take a MIDI note and duration as parameters). These "patches" would be built on top of the Web Audio API.

I'm also thinking that the plugin repo would encourage instrument/effect pull requests from developers, or perhaps create a separate project for gathering such submissions. Basically a way to have the community develop awesome web audio sounds that developers can easily include in their projects.

Thoughts?

**Comment by danigb** [comment]
Hi,

Probably I'm late to the conversation, but I've created https://github.com/danigb/web-audio-assembler that may be relevant to your discussion (if I understood well).
