### ISSUE TITLE
Propose upgrade to <select> element

### ISSUE THREAD

**Issue by paulirish** [h5bp/lazyweb-requests#92]
I think we've seen `<select>` boxes get huge UX upgrades via javascript libraries in the past few years.

The [Chosen](http://harvesthq.github.com/chosen/) project was the first and was later improved on with [select2](https://github.com/ivaynberg/select2#readme)

![image](https://cloud.githubusercontent.com/assets/39191/13403385/9e0e62b6-dec9-11e5-8559-f7a6d49fd144.png)

The idea: let's get this upgrade into browsers. We can make massive UX gains on both desktop and mobile, and kill off javascript that many sites have to ship with.

---
## chosen-style`<select>` control

[demo](http://harvesthq.github.com/chosen/)
#### pitch:

**the interactive select box style popularized by Chosen should be available to the web platform natively.**
### benefits:
- UX
  - visual affordances over implied keyboard interface knowledge
  - searchability in long list
  - multiple selections are more clear
  - essentially backporting modern web app conventions to the `<select>` control
- visible placeholder
- others?
### questions:
- behavior in mobile/touch?
- is it opt-in? if, so probably an attribute on the tag like `<select interactive>`. There's probably a better name.
  - alternatively changing ALL `<select>` to this is more audiacious, but might be fine. 
### todo:
- bounce the idea off #whatwg irc to see if there are any questions that need to be answered for sure in the whatwg list proposal
- investigate pulling scope from [select2](https://github.com/ivaynberg/select2#readme)
- bounce it off [web-standards-dev](http://dev.chromium.org/developers/how-tos/make-a-web-standards-proposal)
- propose it to the whatwg list
  - we can rope in the chosen developers for support and to answer questions as well.
- make a polyfill.
### people involved so far:
- Irakli Nadareishvili - @inadarei - dir of engineering, digital media, NPR  (proposal initiator)
- Paul Irish - Chrome developer relations (facilitator)
- Marcin Wichary  - Chrome designer (idea enjoyer)
- you!

/cc select2 devs: @ivaynberg @ProLoser
/cc chosen devs: @pfiller @mixonic 

<hr>

I think we need some more people to help flesh out the idea. I'm not sure Irakli has the bandwidth to drive this one, so looking for someone else to be the fearless leader.

**Comment by stuartpb** [comment]
I've started a thread for this on the WICG discourse: http://discourse.wicg.io/t/extending-select-a-la-chosen-select2/940
